version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3308:3306"

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6380:6379"
    volumes:
      - ./redis-data:/data
  
  nestjs-api:
    command: ["wait-for-it", "mysql:3307", "--","yarn", "run", "start:dev"]
    build: .
    container_name: nestjs_container
    ports:
      - "3001:3001"
    depends_on:
      - mysql
      - redis
    environment:
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_NAME: ${MYSQL_DATABASE}
      DATABASE_USER: ${MYSQL_USER}
      DATABASE_PASSWORD: ${MYSQL_PASSWORD}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      EMAIL_SMTP_HOST: ${EMAIL_SMTP_HOST}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      NODEMAILER_HOST: ${NODEMAILER_HOST}
      NODEMAILER_PORT: ${NODEMAILER_PORT}
      NODEMAILER_USER: ${NODEMAILER_USER}
      NODEMAILER_PASS: ${NODEMAILER_PASS}
      APP_PORT: 3001
      CORS_ORIGIN: ${CORS_ORIGIN}

  e2e-tests:
    image: nestjs_container   # Use the image built for nestjs-api
    command: ["yarn", "test:e2e"]
    depends_on:
      - nestjs-api
    environment:
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_NAME: ${MYSQL_DATABASE}
      DATABASE_USER: ${MYSQL_USER}
      DATABASE_PASSWORD: ${MYSQL_PASSWORD}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      EMAIL_SMTP_HOST: ${EMAIL_SMTP_HOST}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      NODEMAILER_HOST: ${NODEMAILER_HOST}
      NODEMAILER_PORT: ${NODEMAILER_PORT}
      NODEMAILER_USER: ${NODEMAILER_USER}
      NODEMAILER_PASS: ${NODEMAILER_PASS}
      APP_PORT: 3001
      CORS_ORIGIN: ${CORS_ORIGIN}