version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_challenge
      MYSQL_USER: user_challenge
      MYSQL_PASSWORD: root
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3307:3306"
  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
  
  nestjs-api:
    command: ["wait-for-it", "mysql:3307", "--","yarn", "run", "start:dev"]
    build: .
    container_name: nestjs_container
    ports:
      - "3001:3001"
    depends_on:
      - mysql
      - redis
    env_file:
      - .env

    
