version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
      MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
      MYSQL_USER: ${{ secrets.MYSQL_USER }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3307:3306"

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
  
  nestjs-api:
    command: ["wait-for-it", "mysql:3307", "--","yarn", "run", "start:dev"]
    build: .
    container_name: nestjs_container
    ports:
      - "3001:3001"
    depends_on:
      - mysql
      - redis
    environment:
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_NAME: ${{ secrets.MYSQL_DATABASE }}
      DATABASE_USER: ${{ secrets.MYSQL_USER }}
      DATABASE_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      EMAIL_SMTP_HOST: ${{ secrets.EMAIL_SMTP_HOST }}
      EMAIL_USER: ${{ secrets.EMAIL_USER }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      NODEMAILER_HOST: ${{ secrets.NODEMAILER_HOST }}
      NODEMAILER_PORT: ${{ secrets.NODEMAILER_PORT }}
      NODEMAILER_USER: ${{ secrets.NODEMAILER_USER }}
      NODEMAILER_PASS: ${{ secrets.NODEMAILER_PASS }}
      APP_PORT: 3001
      CORS_ORIGIN: ${{ secrets.CORS_ORIGIN }}